Create Calculator
2024-1-IGRUS-Web-Study/week01 pull request #39
Opened 2024-03-28 12:51 UTC by Beomjeja

일단 계산기만 했는데 제출된건가요...?

2024-03-28 13:27 UTC, Yun-YeoJun commented
@Beomjeja 재범님 PR #38과 #39는 동일한 내용인가요?

2024-03-30 13:55 UTC, Yun-YeoJun commented
@Beomjeja 숫자야구 코드를 제출하실 예정인가요?

만약에 숫자 야구 코드를 제출하실 예정이면, 추후 제출하신 다음에 코드 리뷰 진행하고,
그게 아니라면 계산기 코드만으로 코드 리뷰 진행하겠습니다!

코멘트 남겨주세용

2024-03-31 17:47 UTC, Beomjeja commented
@Yun-YeoJun 네 숫자야구 코드 제출했습니다.

2024-04-01 10:45 UTC, Yun-YeoJun requested changes
@Beomjeja 과제 코드 작성하시느라 고생 많으셨습니다!

전반적으로 자바를 이미 많이 알고 계시는 느낌이 강하게 드는 코드였습니다
1주차에서 다룬 내용으로 드릴 수 있는 리뷰는 몇 개 없는 것 같네요 😂

파일 확장자 수정, 변수명 수정 정도만 하시고 PR 다시 열어주시면 approve 해드리겠습니다~!

수고 많으셨습니다!

2024-04-01 10:45 UTC, Yun-YeoJun commented on 이재범/Calculator
파일 확장자가 없는데, .java로 수정하시면 좋을 것 같아요!

2024-04-01 10:45 UTC, Yun-YeoJun commented on 이재범/Calculator
> +        }
이 문제에서는 if문보다 switch문을 쓰는 게 더 좋은 선택인데 잘 하셨습니다!

참고하실 수 있는 블로그 링크도 함께 첨부합니다.
https://shanepark.tistory.com/395

2024-04-01 10:45 UTC, Yun-YeoJun commented on 이재범/NumberBaseballGame
> +        //bw.flush();
제출할 때는 주석 코드를 삭제하는게 좋습니다!

2024-04-01 10:45 UTC, Yun-YeoJun commented on 이재범/NumberBaseballGame
> +            int b= (int)((Math.random())*10%10);
a, b는 이 변수들이 무슨 용도로 사용되는지 알기 어렵다고 생각합니다.

조금 더 고민해서 이름을 지어보는 건 어떨까요?

2024-04-01 10:45 UTC, Yun-YeoJun commented on 이재범/NumberBaseballGame
> +            String s = bf.readLine();
s도 이름을 바꾸는게 좋을 것 같아요!

2024-04-01 10:45 UTC, Yun-YeoJun commented on 이재범/NumberBaseballGame
두 코드 전체적으로 BufferedReader와 BufferedWriter를 많이 사용하셨네요!

이거는 저의 개인적인 생각인데, 이번 과제에서는 불필요하다는 생각이 듭니다!

두 클래스를 이용한 입출력은 Scanner, System.out.println보다 쓰기 번거롭고 가독성을 포기한 대신에 성능을 선택했다고 생각합니다.

그렇기 때문에 많은 입출력이 발생하고, 성능이 필요한 경우에는 BufferedReader와 BufferedWriter를 사용하는 것이 좋다고 생각합니다.
하지만 입출력에서 고성능이 요구되지 않는 상황에서 두 클래스를 사용하는 것은 오버 엔지니어링이라는 생각이 듭니다.

이런 간단한 상황에서는 편리함과 가독성을 잡기 위해 Scanner, System.out.println과 같은 것들을 사용하는게 더 좋지 않을까 싶습니다..!

물론 어디까지나 저의 생각이기 때문에 다른 의견이 있으시다면 댓글 남겨주세요!!

2024-04-01 10:45 UTC, closed without merging